#!/usr/bin/with-contenv bash

# NOTE - based on https://github.com/linuxserver/docker-webgrabplus/blob/master/root/etc/cont-init.d/30-config
# The default cron schedule can be edited by mounting /config as a volume and tweaking the default file

# comment out PAM
sed -i -e '/pam_loginuid.so/s/^/#/' /etc/pam.d/crond

# add cron file for running feed updates
[[ ! -e /config/update-openvas.cron ]] && \
	cp /defaults/update-openvas.cron /config/update-openvas.cron

# Check environment variable for cron job changes and update config file
if [ "$UPDATE_CRON" ] ; then
  echo "${UPDATE_CRON} /bin/bash /defaults/update-openvas.sh > /dev/stdout" > /config/update-openvas.cron
fi

if [ "$SCHEDULED_UPDATES" ] ; then
  crontab /config/update-openvas.cron
fi

# ospd.conf (note - have to manually specify an ospd.conf file on launch since not running as root to keep from erroring out)
[[ ! -e /config/ospd.conf ]] && \
	cp /defaults/ospd.conf /config/ospd.conf

sed -r -i 's|^(socket_mode[[:blank:]]*=[[:blank:]]*).*|\10o770|' /config/ospd.conf
sed -r -i 's|^(unix_socket[[:blank:]]*=[[:blank:]]*).*|\1/var/run/ospd/ospd.sock|' /config/ospd.conf
sed -r -i 's|^(lock_file_dir[[:blank:]]*=[[:blank:]]*).*|\1/usr/local/var/run|' /config/ospd.conf
sed -r -i 's|^(pid_file[[:blank:]]*=[[:blank:]]*).*|\1/usr/local/var/run/openvas.pid|' /config/ospd.conf
sed -r -i 's|^(log_file[[:blank:]]*=[[:blank:]]*).*|\1/usr/local/var/log/gvm/openvas.log|' /config/ospd.conf

# openvas.conf
[[ ! -e /config/openvas.conf ]] && \
	cp /defaults/openvas.conf /config/openvas.conf
ln -s /config/openvas.conf /usr/local/etc/openvas/openvas.conf

# generate certificates
gvm-manage-certs -a

# disable THP for Redis
echo 'never' > /sys/kernel/mm/transparent_hugepage/enabled && echo 'never' > /sys/kernel/mm/transparent_hugepage

# create directories if necessary
mkdir -p /var/run/ospd
mkdir -p /usr/local/var/lib/openvas/plugins
mkdir -p /usr/local/var/lib/gvm/cert-data
mkdir -p /usr/local/var/lib/gvm/scap-data
mkdir -p /usr/local/var/lib/gvm/data-objects

chown -R abc:abc \
	/config \
	/defaults \
	/var/run/ospd \
	/usr/local/var/run \
	/usr/local/var/log \
	/usr/local/var/lib/gvm/gvmd \
	/usr/local/var/lib/gvm/private \
	/usr/local/var/lib/gvm/CA \
	/usr/local/share/gvm/gvmd/report_formats

chown abc:abc \
	/usr/local/var/lib/openvas/plugins \
	/usr/local/var/lib/gvm/cert-data \
	/usr/local/var/lib/gvm/scap-data \
	/usr/local/var/lib/gvm/data-objects
