#!/usr/bin/with-contenv bash

# NOTE - based on https://github.com/linuxserver/docker-webgrabplus/blob/master/root/etc/cont-init.d/30-config
# The default cron schedule can be edited by mounting /config as a volume and tweaking the default file

# add cron file for running feed updates
[[ ! -e /config/update-cron ]] && \
	cp /defaults/update-cron /config/update-cron

if $SCHEDULED_UPDATES ; then
  crontab -u abc /config/update-cron
fi

# ospd.conf (note - have to manually specify an ospd.conf file on launch since not running as root to keep from erroring out)
[[ ! -e /config/ospd.conf ]] && \
	cp /defaults/ospd.conf /config/ospd.conf

# openvas.conf
[[ ! -e /config/openvas.conf ]] && \
	cp /defaults/openvas.conf /config/openvas.conf
ln -s /config/openvas.conf /usr/local/etc/openvas/openvas.conf

# generate certificates
gvm-manage-certs -a

chown -R abc:abc \
	/config \
	/defaults \
	/usr/local/var/run \
	/usr/local/var/log \
	/usr/local/var/lib/gvm/gvmd \
	/usr/local/var/lib/gvm/private \
	/usr/local/var/lib/gvm/CA

chown abc:abc \
	/usr/local/var/lib/openvas/plugins \
	/usr/local/var/lib/gvm/cert-data \
	/usr/local/var/lib/gvm/scap-data
