#!/usr/bin/with-contenv bash

sleep 5
echo "Attempting to migrate database and create default user"
s6-setuidgid abc gvmd gvm-manage-certs -q -a &> /dev/nul || true
s6-setuidgid abc gvmd --migrate || true
s6-setuidgid abc gvmd --create-user=${GVM_USER} --password=${GVM_PASSWORD} || true

while  [ ! -S /tmp/ospd.sock ]; do
	echo "Greenbone Vulnerability Manager - waiting for OSPD..."
	sleep 10
done

echo "Starting Greenbone Vulnerability Manager..."

exec s6-setuidgid abc gvmd --foreground