#!/bin/bash
set -ueo pipefail

# stolen from https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             -t isaudits/gvm:build-11 build/.

docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             -t isaudits/gvm:base-11 base/.

docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             #-t isaudits/gvm:openvas-7 -t isaudits/gvm:openvas openvas/.
             -t isaudits/gvm:openvas-7 openvas/.

docker build --build-arg VCS_REF="$(git rev-parse --short HEAD)" \
             --build-arg BUILD_DATE="$(date -u +"%Y-%m-%dT%H:%M:%SZ")" \
             #-t isaudits/gvm:gvm-11 -t isaudits/gvm:latest gvm/.
             -t isaudits/gvm:gvm-11 gvm/.