#!/bin/bash
set -ueo pipefail

#docker push isaudits/gvm:build-20.8
#docker push isaudits/gvm:base-20.8
#docker push isaudits/gvm:openvas-20.8
#docker push isaudits/gvm:gvmd-20.8
#docker push isaudits/gvm:gvm-20.8

docker push isaudits/gvm