#!/usr/bin/with-contenv bash

if [ ! -d "/run/redis" ]; then
	mkdir /run/redis/
fi

chown abc:abc /run/redis/

if  [ -S /run/redis/redis.sock ]; then
        rm /run/redis/redis.sock
fi

exec s6-setuidgid abc redis-server --unixsocket /run/redis/redis.sock --unixsocketperm 766 --timeout 0 --databases 128 --maxclients 512 --port 6379 --bind 127.0.0.1

